/*
 * generated by Xtext
 */
package soot.typestate.automata;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AutomataRuntimeModule extends soot.typestate.automata.AbstractAutomataRuntimeModule {

}
