/*
* generated by Xtext
*/
package soot.typestate.automata.contentassist;

import soot.typestate.automata.contentassist.AbstractAutomataProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class AutomataProposalProvider extends AbstractAutomataProposalProvider {

}
