/*
 * generated by Xtext
 */
package soot.typestate.automata;

/**
 * Use this class to register components to be used within the IDE.
 */
public class AutomataUiModule extends soot.typestate.automata.AbstractAutomataUiModule {

}
